//para utilizar estas request es necesaria la extension REST Client
//la cual nos permite hacer peticiones similares a las que hariamos en postman

###traer todas las peliculas
GET http://localhost:3000/movies


###traer una pelicula por id
GET http://localhost:3000/movies/6556d6859ef4868e782a9975

  
###traer una pelicula por genero
GET http://localhost:3000/movies?genre=sci-Fi


###agregar una pelicula 
POST http://localhost:3000/movies
Content-Type: application/json

{
   "title": "Jurassic Park",
    "year": 1993,
    "director": "Steven Spielberg",
    "duration": 127,
    "poster": "https://vice-press.com/cdn/shop/products/Jurassic-Park-Editions-poster-florey.jpg?v=1654518755&width=1024",
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ],
    "rate": 8.1
  }
    


###modificar parcialmente una pelicula
PATCH http://localhost:3000/movies/6556d6859ef4868e782a997c
Content-Type: application/json

{
    "title" : "Jurassic Park 5",
    "year" : 1994
}


###modificar totalmente una pelicula
PUT http://localhost:3000/movies/6556d6859ef4868e782a997c
Content-Type: application/json

{
    "title": "Jurassic Park",
    "year": 1993,
    "director": "Steven Spielberg",
    "duration": 127,
    "poster": "https://vice-press.com/cdn/shop/products/Jurassic-Park-Editions-poster-florey.jpg?v=1654518755&width=1024",
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ],
    "rate": 8.1
}


###
DELETE http://localhost:3000/movies/6556d6859ef4868e782a997c